### ISSUE TITLE
[Security] Workflow release.yml is using vulnerable action s-weigand/setup-conda

### ISSUE THREAD

**Issue by igibek** [s-weigand/setup-conda#185]
The workflow release.yml is referencing action s-weigand/setup-conda using references v1. However this reference is missing the commit [a30654e576ab9e21a25825bf7a5d5f2a9b95b202](https://github.com/s-weigand/setup-conda/commits/a30654e576ab9e21a25825bf7a5d5f2a9b95b202) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by s-weigand** [comment]
The `test-integration` part of `release.yml` just checks that the moving tag `v1` is working after rewriting it.

What the workflow does is:
1. Copy the source code from the tag create at release `vX.Y.Z` to a new tag `original/vX.Y.Z`
2. Transpile the typescript source to a js bundle which will is called when using the action.
3. Overwrite the tag `vX.Y.Z`, and repoint the current `v1` to the overwritten `vX.Y.Z` tag.

a30654e is part of the releases since `v1.0.5`

Feel free to reopen the issue, if I got something fundamentally wrong and this is an actual issue.
