### ISSUE TITLE
PyPy

### ISSUE THREAD

**Issue by phdru** [s-weigand/setup-conda#295]
It it possible to install PyPy (`pypy` for Python 2.7 and `pypy3` for Python 3)?

`python-version: pypy` (with `conda-channels: 'conda-forge'`) doesn't work, the error message is
```text
Error: The value of "python-version" you provided was pypy, which is invalid.
  The value of "python-version" needs to be of form:
  /^\d+\.\d+(\.\d+)?$/
```

In command line the command is
```sh
conda create -c conda-forge -n pypy pypy
```

**Comment by s-weigand** [comment]
Sorry for the late reply, this issue slipped my attention 😓
Since I'm not using `pypy` I didn't account for it when implementing the input validation.
https://github.com/s-weigand/setup-conda/blob/08e09bfa071d6ef2efda341d7792b448d7c6f7f2/src/conda_actions.ts#L279
To support `pypy` and `pypy3` this just needs an additional `else if` in the `install_python` function that checks for `/^pypy((3\.\d+)?(=(\d+)?(\.\d+)?(\.\d+)?)?)?$/` ([see this regex101 example](https://regex101.com/r/Iln42d/1))
and then uses 
```js
await exec.exec('conda', [
        'create',
        '-y',
        '-n',
        '__setup_conda',
        `config.python_version`,
      ])
```
instead of
```js
await exec.exec('conda', [
        'create',
        '-y',
        '-n',
        '__setup_conda',
        `python=${config.python_version}`,
      ])
```

I currently do not have a lot of time so a PR would be very welcome

**Comment by phdru** [comment]
Stuck? Any problem?
