### ISSUE TITLE
Error: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by kumarsuraj9450** [s-weigand/setup-conda#42]
**Describe the bug**
Error: The "path" argument must be of type string. Received type undefined. Why am I getting this and how to solve?
**Expected behavior**
There is no path argument in conda action to provide a path. Error is not clear

**Screenshots**
![image](https://user-images.githubusercontent.com/28962033/98462108-8fd94c00-21d7-11eb-80b5-3857d304ab7f.png)

**Desktop (please complete the following information):**
 - ubuntu-latest
 - chrome

**Comment by s-weigand** [comment]
Hi there thanks for filing this issue, I could identify the root of the problem.
This action was written to run on the default Github containers which already have conda installed, and it uses this installation + the [CONDA environment variable it set](https://github.com/s-weigand/setup-conda/blob/a58eea1d630e12c02ed93a5eee8460d8bed9a823/src/conda_actions.ts#L61) to activate conda.
Your workflow on the other hand is using a [different container](https://github.com/kumarsuraj9450/projectsSite/blob/f6cf128e76dcd92c92925bad4892d53c0bb7177d/.github/workflows/api.yaml#L6) which [doesn't have conda installed and the environment variable set](https://github.com/iterative/cml/tree/master/docker), thus it fails to set the right path.

You might want to use [setup-miniconda](https://github.com/conda-incubator/setup-miniconda) with `miniconda-version: "latest"` instead since this will download and install miniconda in your container. 

I hope this helps you.

**Comment by kumarsuraj9450** [comment]
ok. thanks
